/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.northeastern.cs5500.recipe.controller;

import static com.google.common.truth.Truth.assertThat;
import static com.google.common.truth.Truth.assertWithMessage;

import edu.northeastern.cs5500.recipe.model.Recipe;
import edu.northeastern.cs5500.recipe.repository.MongoDBRepository;
import edu.northeastern.cs5500.recipe.service.MongoDBService;
import org.junit.jupiter.api.Test;

/** Note that this test suite will fail with timeout exceptions if mongodb is not running. */
class DatabaseRecipeControllerTest {
    static MongoDBService mongoDBService;

    RecipeController getRecipeController() {
        if (mongoDBService == null) {
            mongoDBService = new MongoDBService();
        }
        return new RecipeController(new MongoDBRepository<Recipe>(Recipe.class, mongoDBService));
    }

    @Test
    void testRegisterCreatesRecipes() {
        RecipeController recipeController = getRecipeController();
        assertThat(recipeController.getRecipes()).isNotEmpty();
    }

    @Test
    void testRegisterCreatesValidRecipes() {
        RecipeController recipeController = getRecipeController();

        for (Recipe recipe : recipeController.getRecipes()) {
            assertWithMessage(recipe.getTitle()).that(recipe.isValid()).isTrue();
        }
    }

    @Test
    void testCanAddRecipe() {
        // This test should NOT call register
        // TODO: implement this test.
    }

    @Test
    void testCanReplaceRecipe() {
        // This test should NOT call register
        // TODO: implement this test.
    }

    @Test
    void testCanDeleteRecipe() {
        // This test should NOT call register
        // TODO: implement this test
    }
}
