/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.northeastern.cs5500.recipe.controller;

import static com.google.common.truth.Truth.assertThat;
import static com.google.common.truth.Truth.assertWithMessage;

import edu.northeastern.cs5500.recipe.model.Recipe;
import edu.northeastern.cs5500.recipe.repository.InMemoryRepository;
import org.junit.jupiter.api.Test;

class RecipeControllerTest {
    @Test
    void testRegisterCreatesRecipes() {
        RecipeController recipeController = new RecipeController(new InMemoryRepository<Recipe>());
        assertThat(recipeController.getRecipes()).isNotEmpty();
    }

    @Test
    void testRegisterCreatesValidRecipes() {
        RecipeController recipeController = new RecipeController(new InMemoryRepository<Recipe>());

        for (Recipe recipe : recipeController.getRecipes()) {
            assertWithMessage(recipe.getTitle()).that(recipe.isValid()).isTrue();
        }
    }

    @Test
    void testCanAddRecipe() throws Exception {
        RecipeController recipeController = new RecipeController(new InMemoryRepository<Recipe>());

        final Recipe defaultRecipe1 = new Recipe();
        defaultRecipe1.setTitle("Hot dog");
        defaultRecipe1.setCookTime(0);
        defaultRecipe1.setWaitTime(0);
        defaultRecipe1.setPrepTime(0);
        defaultRecipe1.setTotalTime(0);
        recipeController.addRecipe(defaultRecipe1);

        final Recipe defaultRecipe2 = new Recipe();
        defaultRecipe2.setTitle("Hot ");
        System.out.println(defaultRecipe1.getId());

        assertThat(recipeController.getRecipe(defaultRecipe1.getId())).isEqualTo(defaultRecipe1);
    }

    @Test
    void testCanReplaceRecipe() throws Exception {

        RecipeController recipeController = new RecipeController(new InMemoryRepository<Recipe>());

        final Recipe defaultRecipe1 = new Recipe();
        defaultRecipe1.setTitle("Hot dog");
        recipeController.addRecipe(defaultRecipe1);

        final Recipe defaultRecipe2 = new Recipe();
        defaultRecipe2.setTitle("Cold");
        defaultRecipe2.setId(defaultRecipe1.getId());

        for (Recipe recipe : recipeController.getRecipes()) {
            assertThat(recipe).isEqualTo(defaultRecipe1);
        }
        recipeController.updateRecipe(defaultRecipe2);
        for (Recipe recipe : recipeController.getRecipes()) {
            assertThat(recipe).isEqualTo(defaultRecipe2);
            assertThat(recipe).isNotEqualTo(defaultRecipe1);
        }
    }

    @Test
    void testCanDeleteRecipe() throws Exception {

        RecipeController recipeController = new RecipeController(new InMemoryRepository<Recipe>());
        final Recipe defaultRecipe1 = new Recipe();
        defaultRecipe1.setTitle("Hot dog");
        recipeController.addRecipe(defaultRecipe1);

        final Recipe defaultRecipe2 = new Recipe();
        defaultRecipe2.setTitle("Cold");
        recipeController.addRecipe(defaultRecipe2);
        recipeController.deleteRecipe(defaultRecipe1.getId());

        for (Recipe recipe : recipeController.getRecipes()) {
            assertThat(recipe).isEqualTo(defaultRecipe2);
            assertThat(recipe).isNotEqualTo(defaultRecipe1);
        }
    }
}
