/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.northeastern.cs5500.recipe.controller;

import static com.google.common.truth.Truth.assertThat;
import static com.google.common.truth.Truth.assertWithMessage;

import edu.northeastern.cs5500.recipe.model.User;
import org.junit.jupiter.api.Test;

class UserControllerTest {
    private User user;

    @Test
    void testRegisterCreatesUsers() {
        this.user = new User();
        UserController userController = new UserController(user);
        assertThat(userController.getUser()).isEmpty();
        userController.register();
        assertThat(userController.getUser()).isNotEmpty();
    }

    @Test
    void testRegisterCreatesValidUsers() {
        // TODO: Why is this test failing?
        UserController userController = new UserController(user);
        userController.register();

        for (User user : userController.getUser()) {
            assertWithMessage(user.getUserName()).that(user.isValid()).isTrue();
        }
    }

    @Test
    void testCanAddUser() {
        // This test should NOT call register
        // TODO: implement this test.
        UserController userController = new UserController(user);
        
    }

    @Test
    void testCanReplaceUser() {
        // This test should NOT call register
        // TODO: implement this test.

    }

    @Test
    void testCanDeleteUser() {
        // This test should NOT call register
        // TODO: implement this test

    }
}
