/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.northeastern.cs5500.recipe;

import static spark.Spark.*;

public class App {

    static int getAssignedPort() {
        ProcessBuilder processBuilder = new ProcessBuilder();
        if (processBuilder.environment().get("PORT") != null) {
            return Integer.parseInt(processBuilder.environment().get("PORT"));
        }
        return 5000; // run on port 5000 by default
    }

    public static void main(String[] arg) {
        // print all unhandled exceptions
        exception(Exception.class, (e, req, res) -> e.printStackTrace());

        // run on port 5000
        port(getAssignedPort());

        // load and start the server
        DaggerServerComponent.create().server().start();
    }
}
